/**
 * Curated seed dataset for Gustale — dish encyclopedia.
 *
 * Each entry is a complete dish record ready to seed into the database:
 *  - canonical name, slug, short + long description
 *  - origin (lat/lng + country/region entity)
 *  - cuisine category + 1-3 dish-type categories (slug keys only)
 *  - one Wikipedia source URL (the canonical encyclopedia citation)
 *
 * Source of truth for content: Wikipedia (English). The seeder inserts a
 * `sources` row per dish + a `citations` row pointing at the description,
 * so every claim on the live site has an audit trail.
 *
 * To add more dishes: append to DISHES below. The seeder is idempotent —
 * re-running with the same slug is a no-op.
 */

import type { SeedDish } from "./types.js";

export const DISHES: SeedDish[] = [
  // ─── Europe ────────────────────────────────────────────────────────────
  {
    slug: "moussaka-greek",
    canonicalName: "Moussaka",
    shortDescription:
      "A layered casserole of fried eggplant, spiced minced meat, and béchamel sauce, baked until golden. Considered the national dish of Greece.",
    lat: 39.0742,
    lng: 21.8243,
    countryName: "Greece",
    isoCode: "GR",
    cuisineSlug: "greek-cuisine",
    dishTypes: ["casserole", "main-course"],
    wikipediaSlug: "Moussaka",
    originDateEarliest: 1920,
    originDateLatest: 1950,
  },
  {
    slug: "cacio-e-pepe",
    canonicalName: "Cacio e pepe",
    shortDescription:
      "A Roman pasta made with just Pecorino Romano cheese and freshly ground black pepper tossed with hot pasta water and tonnarelli or spaghetti.",
    lat: 41.9028,
    lng: 12.4964,
    countryName: "Italy",
    isoCode: "IT",
    cuisineSlug: "italian-cuisine",
    dishTypes: ["pasta", "main-course"],
    wikipediaSlug: "Cacio_e_pepe",
  },
  {
    slug: "pizza-margherita",
    canonicalName: "Pizza Margherita",
    shortDescription:
      "A Neapolitan pizza topped with San Marzano tomato sauce, fresh mozzarella, fresh basil, and olive oil. Named for Queen Margherita of Savoy in 1889.",
    lat: 40.8518,
    lng: 14.2681,
    countryName: "Italy",
    isoCode: "IT",
    cuisineSlug: "italian-cuisine",
    dishTypes: ["bread", "main-course"],
    wikipediaSlug: "Pizza_Margherita",
    originDateEarliest: 1889,
    originDateLatest: 1889,
  },
  {
    slug: "paella-valenciana",
    canonicalName: "Paella",
    shortDescription:
      "A Valencian rice dish with saffron, olive oil, vegetables, and a choice of seafood, meat, or beans. Cooked in a wide, shallow pan over an open fire.",
    lat: 39.4699,
    lng: -0.3763,
    countryName: "Spain",
    isoCode: "ES",
    cuisineSlug: "spanish-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Paella",
  },
  {
    slug: "gazpacho",
    canonicalName: "Gazpacho",
    shortDescription:
      "A cold Andalusian soup made from raw blended vegetables — typically tomato, cucumber, pepper, garlic, olive oil, vinegar, and stale bread.",
    lat: 37.3891,
    lng: -5.9845,
    countryName: "Spain",
    isoCode: "ES",
    cuisineSlug: "spanish-cuisine",
    dishTypes: ["soup", "appetizer"],
    wikipediaSlug: "Gazpacho",
  },
  {
    slug: "tarte-tatin",
    canonicalName: "Tarte Tatin",
    shortDescription:
      "An upside-down French tart in which apples are caramelised in butter and sugar beneath a pastry crust, then flipped when served.",
    lat: 47.9025,
    lng: 1.909,
    countryName: "France",
    isoCode: "FR",
    cuisineSlug: "french-cuisine",
    dishTypes: ["dessert"],
    wikipediaSlug: "Tarte_Tatin",
    originDateEarliest: 1880,
    originDateLatest: 1900,
  },
  {
    slug: "boeuf-bourguignon",
    canonicalName: "Boeuf bourguignon",
    shortDescription:
      "A French beef stew braised in red wine (traditionally Burgundy) with beef broth, bacon, onions, mushrooms, and a bouquet garni.",
    lat: 47.2805,
    lng: 4.9994,
    countryName: "France",
    isoCode: "FR",
    cuisineSlug: "french-cuisine",
    dishTypes: ["stew", "main-course"],
    wikipediaSlug: "Boeuf_bourguignon",
  },
  {
    slug: "wiener-schnitzel",
    canonicalName: "Wiener Schnitzel",
    shortDescription:
      "A thin, breaded, pan-fried veal cutlet, traditionally served in Austria with a slice of lemon and either potato salad or parsley potatoes.",
    lat: 48.2082,
    lng: 16.3738,
    countryName: "Austria",
    isoCode: "AT",
    cuisineSlug: "austrian-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Wiener_Schnitzel",
  },
  {
    slug: "pierogi",
    canonicalName: "Pierogi",
    shortDescription:
      "Filled dumplings of unleavened dough, traditionally stuffed with potato, sauerkraut, meat, cheese, or fruit. A staple of Polish cuisine.",
    lat: 52.2297,
    lng: 21.0122,
    countryName: "Poland",
    isoCode: "PL",
    cuisineSlug: "polish-cuisine",
    dishTypes: ["dumpling", "main-course"],
    wikipediaSlug: "Pierogi",
  },
  {
    slug: "goulash-hungarian",
    canonicalName: "Goulash",
    shortDescription:
      "A Hungarian soup or stew of meat and vegetables seasoned with paprika and other spices. The name derives from the Hungarian word gulyás, meaning 'herdsman'.",
    lat: 47.4979,
    lng: 19.0402,
    countryName: "Hungary",
    isoCode: "HU",
    cuisineSlug: "hungarian-cuisine",
    dishTypes: ["stew", "soup", "main-course"],
    wikipediaSlug: "Goulash",
  },

  // ─── East & Southeast Asia ────────────────────────────────────────────
  {
    slug: "ramen-japanese",
    canonicalName: "Ramen",
    shortDescription:
      "A Japanese noodle soup with wheat noodles in a meat- or fish-based broth, flavoured with soy sauce or miso and topped with ingredients like sliced pork, nori, and scallions.",
    lat: 35.6762,
    lng: 139.6503,
    countryName: "Japan",
    isoCode: "JP",
    cuisineSlug: "japanese-cuisine",
    dishTypes: ["noodle-soup", "main-course"],
    wikipediaSlug: "Ramen",
  },
  {
    slug: "sushi",
    canonicalName: "Sushi",
    shortDescription:
      "A traditional Japanese dish of vinegared rice paired with various ingredients, most commonly raw seafood, vegetables, and sometimes tropical fruits.",
    lat: 35.6762,
    lng: 139.6503,
    countryName: "Japan",
    isoCode: "JP",
    cuisineSlug: "japanese-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Sushi",
  },
  {
    slug: "pad-thai",
    canonicalName: "Pad Thai",
    shortDescription:
      "A stir-fried rice noodle dish from Thailand with eggs, vegetables, tofu or shrimp, peanuts, and a tangy sauce of tamarind, fish sauce, and palm sugar.",
    lat: 13.7563,
    lng: 100.5018,
    countryName: "Thailand",
    isoCode: "TH",
    cuisineSlug: "thai-cuisine",
    dishTypes: ["stir-fry", "noodle-soup", "main-course"],
    wikipediaSlug: "Pad_Thai",
    originDateEarliest: 1930,
    originDateLatest: 1940,
  },
  {
    slug: "tom-yum",
    canonicalName: "Tom Yum",
    shortDescription:
      "A hot and sour Thai soup with shrimp, lemongrass, kaffir lime leaves, galangal, lime juice, fish sauce, and crushed chili peppers.",
    lat: 13.7563,
    lng: 100.5018,
    countryName: "Thailand",
    isoCode: "TH",
    cuisineSlug: "thai-cuisine",
    dishTypes: ["soup", "main-course"],
    wikipediaSlug: "Tom_yum",
  },
  {
    slug: "pho-vietnamese",
    canonicalName: "Phở",
    shortDescription:
      "A Vietnamese noodle soup of bone broth, rice noodles, herbs, and meat (typically beef or chicken). Considered Vietnam's national dish.",
    lat: 21.0285,
    lng: 105.8542,
    countryName: "Vietnam",
    isoCode: "VN",
    cuisineSlug: "vietnamese-cuisine",
    dishTypes: ["noodle-soup", "main-course"],
    wikipediaSlug: "Ph%E1%BB%9F",
    originDateEarliest: 1900,
    originDateLatest: 1920,
  },
  {
    slug: "banh-mi",
    canonicalName: "Bánh mì",
    shortDescription:
      "A Vietnamese sandwich of a short baguette with grilled pork, pâté, pickled vegetables, fresh herbs, and chili. A legacy of French colonial rule.",
    lat: 21.0285,
    lng: 105.8542,
    countryName: "Vietnam",
    isoCode: "VN",
    cuisineSlug: "vietnamese-cuisine",
    dishTypes: ["sandwich", "main-course"],
    wikipediaSlug: "B%C3%A1nh_m%C3%AC",
    originDateEarliest: 1890,
    originDateLatest: 1910,
  },
  {
    slug: "hainanese-chicken-rice",
    canonicalName: "Hainanese Chicken Rice",
    shortDescription:
      "A dish of poached chicken served with seasoned rice cooked in chicken broth, accompanied by cucumber, chili sauce, and ginger paste.",
    lat: 1.3521,
    lng: 103.8198,
    countryName: "Singapore",
    isoCode: "SG",
    cuisineSlug: "singaporean-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Hainanese_chicken_rice",
  },
  {
    slug: "nasi-goreng",
    canonicalName: "Nasi Goreng",
    shortDescription:
      "An Indonesian fried rice dish cooked with kecap manis (sweet soy sauce), shallots, garlic, tamarind, and chilli, typically topped with a fried egg.",
    lat: -6.2088,
    lng: 106.8456,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["fried-rice", "main-course"],
    wikipediaSlug: "Nasi_goreng",
  },
  {
    slug: "bibimbap",
    canonicalName: "Bibimbap",
    shortDescription:
      "A Korean rice dish of steamed white rice topped with sautéed and seasoned vegetables, beef, a raw or fried egg, and gochujang (chilli paste).",
    lat: 37.5665,
    lng: 126.978,
    countryName: "South Korea",
    isoCode: "KR",
    cuisineSlug: "korean-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Bibimbap",
  },
  {
    slug: "kimchi-jjigae",
    canonicalName: "Kimchi Jjigae",
    shortDescription:
      "A Korean stew made with aged kimchi, pork or tuna, tofu, scallions, and gochujang, simmered together until bubbling and tangy.",
    lat: 37.5665,
    lng: 126.978,
    countryName: "South Korea",
    isoCode: "KR",
    cuisineSlug: "korean-cuisine",
    dishTypes: ["stew", "soup", "main-course"],
    wikipediaSlug: "Kimchi_jjigae",
  },

  // ─── Middle East & South Asia ─────────────────────────────────────────
  {
    slug: "hummus",
    canonicalName: "Hummus",
    shortDescription:
      "A Levantine dip or spread made from cooked, mashed chickpeas blended with tahini, lemon juice, garlic, and olive oil.",
    lat: 31.7683,
    lng: 35.2137,
    countryName: "Israel",
    isoCode: "IL",
    cuisineSlug: "israeli-cuisine",
    dishTypes: ["appetizer", "sauce"],
    wikipediaSlug: "Hummus",
  },
  {
    slug: "falafel",
    canonicalName: "Falafel",
    shortDescription:
      "Deep-fried balls or patties of ground chickpeas, fava beans, or both, mixed with herbs and spices. A staple of Middle Eastern street food.",
    lat: 31.7683,
    lng: 35.2137,
    countryName: "Israel",
    isoCode: "IL",
    cuisineSlug: "israeli-cuisine",
    dishTypes: ["appetizer", "main-course"],
    wikipediaSlug: "Falafel",
  },
  {
    slug: "shawarma",
    canonicalName: "Shawarma",
    shortDescription:
      "A Middle Eastern dish of slow-roasted, thinly sliced meat (lamb, mutton, beef, chicken, or mixed) served in a flatbread with vegetables and tahini or yogurt sauce.",
    lat: 33.8938,
    lng: 35.5018,
    countryName: "Lebanon",
    isoCode: "LB",
    cuisineSlug: "lebanese-cuisine",
    dishTypes: ["sandwich", "main-course"],
    wikipediaSlug: "Shawarma",
  },
  {
    slug: "biryani-hyderabadi",
    canonicalName: "Hyderabadi Biryani",
    shortDescription:
      "A mixed rice dish of layered basmati rice, marinated meat (typically chicken, mutton, or goat), fried onions, saffron, and whole spices. The Hyderabadi version is among the most famous.",
    lat: 17.385,
    lng: 78.4867,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "indian-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Biryani",
  },
  {
    slug: "chicken-tikka-masala",
    canonicalName: "Chicken Tikka Masala",
    shortDescription:
      "A dish of roasted marinated chicken chunks (chicken tikka) in a spiced, creamy tomato sauce. Often considered a British national dish due to its invention in Glasgow.",
    lat: 55.8642,
    lng: -4.2518,
    countryName: "United Kingdom",
    isoCode: "GB",
    cuisineSlug: "british-cuisine",
    dishTypes: ["curry", "main-course"],
    wikipediaSlug: "Chicken_tikka_masala",
    originDateEarliest: 1960,
    originDateLatest: 1970,
  },

  // ─── Americas ──────────────────────────────────────────────────────────
  {
    slug: "feijoada",
    canonicalName: "Feijoada",
    shortDescription:
      "A Brazilian stew of black beans with pork and beef, served with rice, collard greens, farofa (toasted cassava flour), and orange slices.",
    lat: -22.9068,
    lng: -43.1729,
    countryName: "Brazil",
    isoCode: "BR",
    cuisineSlug: "brazilian-cuisine",
    dishTypes: ["stew", "main-course"],
    wikipediaSlug: "Feijoada",
  },
  {
    slug: "ceviche-peruvian",
    canonicalName: "Ceviche",
    shortDescription:
      "A Peruvian dish of raw fish cured in fresh citrus juices (typically lime), spiced with ají or chili peppers, and seasoned with onions, salt, and cilantro.",
    lat: -12.0464,
    lng: -77.0428,
    countryName: "Peru",
    isoCode: "PE",
    cuisineSlug: "peruvian-cuisine",
    dishTypes: ["appetizer", "main-course"],
    wikipediaSlug: "Ceviche",
  },
  {
    slug: "hamburger-american",
    canonicalName: "Hamburger",
    shortDescription:
      "A sandwich consisting of a cooked ground-meat patty (usually beef) between two pieces of bread or a bun. The modern form is most associated with the United States.",
    lat: 39.8283,
    lng: -98.5795,
    countryName: "United States",
    isoCode: "US",
    cuisineSlug: "american-cuisine",
    dishTypes: ["sandwich", "main-course"],
    wikipediaSlug: "Hamburger",
  },
  {
    slug: "poutine",
    canonicalName: "Poutine",
    shortDescription:
      "A Québécois dish of french fries topped with cheese curds and hot gravy. Originated in rural Quebec in the 1950s.",
    lat: 46.8139,
    lng: -71.208,
    countryName: "Canada",
    isoCode: "CA",
    cuisineSlug: "canadian-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Poutine",
    originDateEarliest: 1950,
    originDateLatest: 1960,
  },

  // ─── Africa ────────────────────────────────────────────────────────────
  {
    slug: "tagine-moroccan",
    canonicalName: "Tagine",
    shortDescription:
      "A slow-cooked North African stew named after the conical clay pot in which it is cooked. Combines meat (typically lamb or chicken) with vegetables, fruits, and warming spices.",
    lat: 33.9716,
    lng: -6.8498,
    countryName: "Morocco",
    isoCode: "MA",
    cuisineSlug: "moroccan-cuisine",
    dishTypes: ["stew", "main-course"],
    wikipediaSlug: "Tagine",
  },
  {
    slug: "jollof-rice",
    canonicalName: "Jollof Rice",
    shortDescription:
      "A West African one-pot rice dish of long-grain rice simmered in a tomato-and-red-pepper sauce with onions, garlic, ginger, thyme, and assorted proteins.",
    lat: 6.5244,
    lng: 3.3792,
    countryName: "Nigeria",
    isoCode: "NG",
    cuisineSlug: "nigerian-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Jollof_rice",
  },

  // ─── Southeast Asia — Indonesia & Bali ────────────────────────────────
  {
    slug: "babi-guling",
    canonicalName: "Babi Guling",
    shortDescription:
      "A Balinese whole-roasted suckling pig stuffed with a spice paste of turmeric, coriander, galangal, garlic, and chili, spit-roasted over coconut husk fire until the skin crackles.",
    lat: -8.4095,
    lng: 115.1889,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["main-course", "kebab"],
    wikipediaSlug: "Babi_guling",
  },
  {
    slug: "rendang",
    canonicalName: "Rendang",
    shortDescription:
      "A West Sumatran dry curry of beef slow-cooked for hours in coconut milk and a paste of ginger, galangal, turmeric, chili, lemongrass, garlic, and shallots until the sauce fully reduces and the meat darkens.",
    lat: -0.7893,
    lng: 100.6544,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["curry", "stew", "main-course"],
    wikipediaSlug: "Rendang",
  },
  {
    slug: "soto-ayam",
    canonicalName: "Soto Ayam",
    shortDescription:
      "An Indonesian clear chicken soup fragrant with turmeric, lemongrass, and lime leaves, served with rice or vermicelli, shredded chicken, boiled egg, bean sprouts, and crispy shallots.",
    lat: -6.2088,
    lng: 106.8456,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["soup", "main-course"],
    wikipediaSlug: "Soto_ayam",
  },
  {
    slug: "rawon",
    canonicalName: "Rawon",
    shortDescription:
      "An East Javanese beef soup with a deep black color from keluak nuts, seasoned with garlic, shallots, ginger, turmeric, and aromatic leaves.",
    lat: -7.2459,
    lng: 112.7378,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["soup", "main-course"],
    wikipediaSlug: "Rawon",
  },
  {
    slug: "gado-gado",
    canonicalName: "Gado-Gado",
    shortDescription:
      "An Indonesian salad of blanched and steamed vegetables, hard-boiled egg, fried tofu, and lontong, dressed in a peanut sauce sweetened with palm sugar and spiked with chili and tamarind.",
    lat: -6.1751,
    lng: 106.865,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["salad", "main-course"],
    wikipediaSlug: "Gado-gado",
  },
  {
    slug: "pempek",
    canonicalName: "Pempek",
    shortDescription:
      "Palembang fish cakes made from ground mackerel or other white fish mixed with tapioca flour, formed into logs or balls, boiled, sliced, and fried, served with a sweet-sour-spicy cuko sauce.",
    lat: -2.9909,
    lng: 104.7567,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["appetizer", "main-course"],
    wikipediaSlug: "Pempek",
  },
  {
    slug: "nasi-campur-bali",
    canonicalName: "Nasi Campur Bali",
    shortDescription:
      "A Balinese rice plate featuring a small mound of white rice surrounded by several small portions: a meat or fish, vegetables, peanut sauce, fried shallots, shredded coconut, sambal, and a small portion of lawar.",
    lat: -8.65,
    lng: 115.2167,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Nasi_campur",
  },
  {
    slug: "sate-lilit",
    canonicalName: "Sate Lilit",
    shortDescription:
      "A Balinese minced-meat satay: finely ground pork, chicken, or fish mixed with grated coconut, coconut milk, lime leaves, lemongrass, and spices, molded around bamboo skewers and grilled over coconut charcoal.",
    lat: -8.5069,
    lng: 115.2625,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["kebab", "appetizer"],
    wikipediaSlug: "Sate_lilit",
  },

  // ─── Southeast Asia — broader ─────────────────────────────────────────
  {
    slug: "laksa",
    canonicalName: "Laksa",
    shortDescription:
      "A spicy noodle soup of Peranakan and broader Southeast Asian origin: rice vermicelli or thick wheat noodles in a fragrant broth built from lemongrass, galangal, candlenuts, turmeric, and dried shrimp, topped with bean sprouts, prawns, and hard-boiled egg.",
    lat: 1.3521,
    lng: 103.8198,
    countryName: "Singapore",
    isoCode: "SG",
    cuisineSlug: "singaporean-cuisine",
    dishTypes: ["noodle-soup", "soup", "main-course"],
    wikipediaSlug: "Laksa",
  },
  {
    slug: "khao-soi",
    canonicalName: "Khao Soi",
    shortDescription:
      "A Northern Thai coconut-curry noodle soup of soft egg noodles in a turmeric-and-chili coconut broth, topped with crispy fried noodles, chicken or beef, pickled mustard greens, shallots, and lime.",
    lat: 18.7883,
    lng: 98.9853,
    countryName: "Thailand",
    isoCode: "TH",
    cuisineSlug: "northern-thai-cuisine",
    dishTypes: ["noodle-soup", "curry", "main-course"],
    wikipediaSlug: "Khao_soi",
  },

  // ─── East Asia ─────────────────────────────────────────────────────────
  {
    slug: "udon",
    canonicalName: "Udon",
    shortDescription:
      "Thick Japanese wheat noodles served in a light dashi-based broth, often with toppings such as tempura, sliced scallion, or a soft-boiled egg. Related to ramen but chewier and usually served in a milder broth.",
    lat: 34.6937,
    lng: 135.5023,
    countryName: "Japan",
    isoCode: "JP",
    cuisineSlug: "japanese-cuisine",
    dishTypes: ["noodle-soup", "main-course"],
    wikipediaSlug: "Udon",
  },
  {
    slug: "mapo-tofu",
    canonicalName: "Mapo Tofu",
    shortDescription:
      "A Sichuan dish of silken tofu simmered in a fiery red sauce of fermented broad-bean paste (doubanjiang), ground pork or beef, douchi, Sichuan peppercorns, chili oil, and scallions.",
    lat: 30.5728,
    lng: 104.0668,
    countryName: "China",
    isoCode: "CN",
    cuisineSlug: "chinese-cuisine",
    dishTypes: ["stew", "main-course"],
    wikipediaSlug: "Mapo_tofu",
  },
  {
    slug: "congee",
    canonicalName: "Congee",
    shortDescription:
      "A long-simmered rice porridge eaten across East and Southeast Asia, served plain or with pickles, century egg, shredded pork, fish, or scallions. Cantonese jook, Japanese okayu, and Indonesian bubur are all forms.",
    lat: 23.1291,
    lng: 113.2644,
    countryName: "China",
    isoCode: "CN",
    cuisineSlug: "chinese-cuisine",
    dishTypes: ["soup", "main-course"],
    wikipediaSlug: "Congee",
  },
  {
    slug: "jiaozi",
    canonicalName: "Jiaozi",
    shortDescription:
      "Northern Chinese crescent-shaped dumplings with a thin wheat-flour wrapper and a filling of ground pork, cabbage, ginger, scallions, and soy sauce. Boiled (shuijiao), steamed (zhengjiao), or pan-fried (guotie).",
    lat: 39.9042,
    lng: 116.4074,
    countryName: "China",
    isoCode: "CN",
    cuisineSlug: "chinese-cuisine",
    dishTypes: ["dumpling", "main-course"],
    wikipediaSlug: "Jiaozi",
  },
  {
    slug: "japchae",
    canonicalName: "Japchae",
    shortDescription:
      "A Korean stir-fried glass-noodle dish made from sweet-potato starch noodles tossed with beef, spinach, mushrooms, carrots, and onion in a sesame-oil and soy sauce dressing.",
    lat: 37.5665,
    lng: 126.978,
    countryName: "South Korea",
    isoCode: "KR",
    cuisineSlug: "korean-cuisine",
    dishTypes: ["stir-fry", "noodle-soup", "main-course"],
    wikipediaSlug: "Japchae",
  },

  // ─── South / Central Asia ──────────────────────────────────────────────
  {
    slug: "dosa",
    canonicalName: "Dosa",
    shortDescription:
      "A thin, crispy South Indian crepe made from a fermented batter of rice and urad dal, served with coconut chutney and sambar. Sambar is closely related to the rasam and other lentil-stew traditions of the Deccan.",
    lat: 13.0827,
    lng: 80.2707,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "south-indian-cuisine",
    dishTypes: ["pancake", "main-course"],
    wikipediaSlug: "Dosa",
  },
  {
    slug: "vindaloo",
    canonicalName: "Vindaloo",
    shortDescription:
      "A Goan curry of Portuguese origin: meat (traditionally pork) marinated in vinegar, garlic, and Kashmiri chili, then cooked with onions, ginger, and warm spices. The Portuguese carne de vinha d'alhos became vindaloo over centuries.",
    lat: 15.2993,
    lng: 74.124,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "goan-cuisine",
    dishTypes: ["curry", "main-course"],
    wikipediaSlug: "Vindaloo",
  },
  {
    slug: "momo",
    canonicalName: "Momo",
    shortDescription:
      "A Himalayan steamed dumpling of Tibetan origin, made from a thin wheat-flour wrapper and a filling of ground meat or vegetables. Now widely eaten across Nepal, Sikkim, Bhutan, and the Tibetan diaspora.",
    lat: 27.7172,
    lng: 85.324,
    countryName: "Nepal",
    isoCode: "NP",
    cuisineSlug: "nepali-cuisine",
    dishTypes: ["dumpling", "appetizer"],
    wikipediaSlug: "Momo_(dumpling)",
  },

  // ─── Europe ────────────────────────────────────────────────────────────
  {
    slug: "risotto-alla-milanese",
    canonicalName: "Risotto alla Milanese",
    shortDescription:
      "A Northern Italian short-grain rice dish cooked in a bone-marrow-enriched beef broth with saffron and onions, giving it a deep yellow color and a faintly metallic, floral finish.",
    lat: 45.4642,
    lng: 9.19,
    countryName: "Italy",
    isoCode: "IT",
    cuisineSlug: "italian-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Risotto_alla_milanese",
  },
  {
    slug: "couscous",
    canonicalName: "Couscous",
    shortDescription:
      "Tiny steamed semolina grains of Maghrebi origin, served beneath or alongside a stew of meat (typically lamb or chicken) and vegetables flavored with ras el hanout, saffron, and preserved lemon.",
    lat: 36.8065,
    lng: 10.1815,
    countryName: "Tunisia",
    isoCode: "TN",
    cuisineSlug: "maghrebi-cuisine",
    dishTypes: ["stew", "main-course"],
    wikipediaSlug: "Couscous",
  },
  {
    slug: "shakshuka",
    canonicalName: "Shakshuka",
    shortDescription:
      "Eggs poached in a spiced sauce of tomatoes, peppers, onions, garlic, and chili. Origin disputed between North African and Levantine kitchens; eaten across Israel, Tunisia, Libya, and the Maghreb.",
    lat: 32.0853,
    lng: 34.7818,
    countryName: "Israel",
    isoCode: "IL",
    cuisineSlug: "israeli-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Shakshuka",
  },
  {
    slug: "mansaf",
    canonicalName: "Mansaf",
    shortDescription:
      "The national dish of Jordan: lamb cooked in a fermented dried-yogurt sauce (jameed) and served over a flatbread (shrak) topped with rice and almonds. Central to Bedouin hospitality.",
    lat: 31.9454,
    lng: 35.9284,
    countryName: "Jordan",
    isoCode: "JO",
    cuisineSlug: "jordanian-cuisine",
    dishTypes: ["stew", "main-course"],
    wikipediaSlug: "Mansaf",
  },
  {
    slug: "borscht",
    canonicalName: "Borscht",
    shortDescription:
      "A sour soup of Eastern European origin built on beetroots, which give it a deep red color, combined with cabbage, potatoes, carrots, onion, and a meat broth. Often served with sour cream and pampushky.",
    lat: 50.4501,
    lng: 30.5234,
    countryName: "Ukraine",
    isoCode: "UA",
    cuisineSlug: "ukrainian-cuisine",
    dishTypes: ["soup", "main-course"],
    wikipediaSlug: "Borscht",
  },
  {
    slug: "bacalhau-a-bras",
    canonicalName: "Bacalhau à Brás",
    shortDescription:
      "A Portuguese dish of shredded salt cod stir-fried with onions, matchstick potatoes, parsley, olives, and eggs, finished with black olives and a squeeze of lemon.",
    lat: 38.7223,
    lng: -9.1393,
    countryName: "Portugal",
    isoCode: "PT",
    cuisineSlug: "portuguese-cuisine",
    dishTypes: ["stir-fry", "main-course"],
    wikipediaSlug: "Bacalhau_%C3%A0_Br%C3%A1s",
  },
  {
    slug: "tiramisu",
    canonicalName: "Tiramisù",
    shortDescription:
      "A layered Italian dessert of espresso-soaked savoiardi biscuits and a mascarpone cream, dusted with cocoa. Origins contested between Veneto and Friuli-Venezia Giulia; emerged in its modern form in the 1960s–80s.",
    lat: 45.4408,
    lng: 12.3155,
    countryName: "Italy",
    isoCode: "IT",
    cuisineSlug: "italian-cuisine",
    dishTypes: ["dessert"],
    wikipediaSlug: "Tiramis%C3%B9",
  },

  // ─── Americas ──────────────────────────────────────────────────────────
  {
    slug: "tamales",
    canonicalName: "Tamales",
    shortDescription:
      "Masa (nixtamalized corn dough) filled with meat, cheese, beans, or chilies, wrapped in a corn husk or banana leaf and steamed. Found across Mexico, Guatemala, and much of Central America; deeply rooted in Mesoamerican cooking.",
    lat: 19.4326,
    lng: -99.1332,
    countryName: "Mexico",
    isoCode: "MX",
    cuisineSlug: "mexican-cuisine",
    dishTypes: ["main-course", "appetizer"],
    wikipediaSlug: "Tamale",
  },
  {
    slug: "empanada",
    canonicalName: "Empanada",
    shortDescription:
      "A baked or fried pastry turnover filled with seasoned meat, cheese, or vegetables. Found across Latin America from Argentina to the Philippines, each region claiming its own folded style and filling.",
    lat: -34.6037,
    lng: -58.3816,
    countryName: "Argentina",
    isoCode: "AR",
    cuisineSlug: "argentine-cuisine",
    dishTypes: ["appetizer", "main-course"],
    wikipediaSlug: "Empanada",
  },
  {
    slug: "tostones",
    canonicalName: "Tostones",
    shortDescription:
      "Twice-fried green-plantain slices, flattened between fryings. A staple across the Caribbean and Latin American coastlines, served as a side or snack, often with garlic mojo or a saltfish topping.",
    lat: 18.4655,
    lng: -66.1057,
    countryName: "Puerto Rico",
    isoCode: "PR",
    cuisineSlug: "caribbean-cuisine",
    dishTypes: ["appetizer", "side"],
    wikipediaSlug: "Tostones",
  },
  {
    slug: "acaraje",
    canonicalName: "Acarajé",
    shortDescription:
      "A Bahian (Brazilian) street food of black-eyed pea fritters split open and stuffed with vatapá (a shrimp and peanut paste), dried shrimp, and a bright salad of tomato, onion, and cilantro.",
    lat: -12.9714,
    lng: -38.5014,
    countryName: "Brazil",
    isoCode: "BR",
    cuisineSlug: "bahian-cuisine",
    dishTypes: ["appetizer", "street-snack"],
    wikipediaSlug: "Acaraj%C3%A9",
  },

  // ─── Network expansion — 60 additional dishes ─────────────────────────
  // These entries deliberately span the existing food-network regions and
  // include the missing anchors already referenced by DISH_RELATIONS.
  {
    slug: "moussaka-levant",
    canonicalName: "Levantine Moussaka",
    shortDescription:
      "A Levantine eggplant dish in which roasted eggplant is cooked with tomatoes, chickpeas, onions, garlic, and warm spices. Unlike the Greek casserole, it is usually served as a vegetable mezze or main dish without béchamel.",
    lat: 33.8938,
    lng: 35.5018,
    countryName: "Lebanon",
    isoCode: "LB",
    cuisineSlug: "lebanese-cuisine",
    dishTypes: ["casserole", "main-course"],
    wikipediaSlug: "Moussaka",
  },
  {
    slug: "baba-ganoush",
    canonicalName: "Baba ganoush",
    shortDescription:
      "A Levantine dip of fire-roasted eggplant blended with tahini, lemon juice, garlic, and olive oil, often finished with parsley or pomegranate seeds.",
    lat: 33.8938,
    lng: 35.5018,
    countryName: "Lebanon",
    isoCode: "LB",
    cuisineSlug: "lebanese-cuisine",
    dishTypes: ["appetizer", "sauce"],
    wikipediaSlug: "Baba_ghanoush",
  },
  {
    slug: "kofta",
    canonicalName: "Kofta",
    shortDescription:
      "Seasoned ground meat shaped into balls, patties, or logs and grilled, fried, or braised across the Middle East, South Asia, Central Asia, and the Mediterranean.",
    lat: 33.8938,
    lng: 35.5018,
    countryName: "Lebanon",
    isoCode: "LB",
    cuisineSlug: "lebanese-cuisine",
    dishTypes: ["kebab", "main-course"],
    wikipediaSlug: "Kofta",
  },
  {
    slug: "kibbeh",
    canonicalName: "Kibbeh",
    shortDescription:
      "A Levantine preparation of bulgur, minced onions, and finely ground meat, shaped into shells or patties and baked, fried, or served raw depending on the regional style.",
    lat: 34.4367,
    lng: 35.8497,
    countryName: "Lebanon",
    isoCode: "LB",
    cuisineSlug: "lebanese-cuisine",
    dishTypes: ["appetizer", "main-course"],
    wikipediaSlug: "Kibbeh",
  },
  {
    slug: "tabbouleh",
    canonicalName: "Tabbouleh",
    shortDescription:
      "A Levantine herb salad built around finely chopped parsley, tomato, mint, onion, and bulgur dressed with lemon juice and olive oil.",
    lat: 33.8938,
    lng: 35.5018,
    countryName: "Lebanon",
    isoCode: "LB",
    cuisineSlug: "lebanese-cuisine",
    dishTypes: ["salad", "appetizer"],
    wikipediaSlug: "Tabbouleh",
  },
  {
    slug: "fattoush",
    canonicalName: "Fattoush",
    shortDescription:
      "A Levantine bread salad of lettuce and seasonal vegetables tossed with toasted or fried pieces of pita, lemon, olive oil, and sumac.",
    lat: 33.8938,
    lng: 35.5018,
    countryName: "Lebanon",
    isoCode: "LB",
    cuisineSlug: "lebanese-cuisine",
    dishTypes: ["salad", "appetizer"],
    wikipediaSlug: "Fattoush",
  },
  {
    slug: "dolma",
    canonicalName: "Dolma",
    shortDescription:
      "A family of stuffed vegetable and vine-leaf dishes filled with rice, herbs, meat, or grains, then simmered or braised in the cuisines of the eastern Mediterranean and Near East.",
    lat: 39.9334,
    lng: 32.8597,
    countryName: "Turkey",
    isoCode: "TR",
    cuisineSlug: "turkish-cuisine",
    dishTypes: ["appetizer", "main-course"],
    wikipediaSlug: "Dolma",
  },
  {
    slug: "menemen",
    canonicalName: "Menemen",
    shortDescription:
      "A Turkish breakfast of softly scrambled eggs cooked with tomatoes, green peppers, olive oil, and spices, sometimes enriched with onion, cheese, or sucuk.",
    lat: 38.4237,
    lng: 27.1428,
    countryName: "Turkey",
    isoCode: "TR",
    cuisineSlug: "turkish-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Menemen_(food)",
  },
  {
    slug: "doner-kebab",
    canonicalName: "Döner kebab",
    shortDescription:
      "Seasoned meat stacked on a vertical spit, slowly roasted and shaved to order, then served in bread or a flatbread with vegetables, herbs, and sauces.",
    lat: 41.0082,
    lng: 28.9784,
    countryName: "Turkey",
    isoCode: "TR",
    cuisineSlug: "turkish-cuisine",
    dishTypes: ["kebab", "sandwich", "main-course"],
    wikipediaSlug: "D%C3%B6ner",
  },
  {
    slug: "musakka-turkish",
    canonicalName: "Musakka",
    shortDescription:
      "A Turkish aubergine dish of fried slices in tomato-pepper meat sauce, typically without béchamel and often served with pilav.",
    // Same Istanbul centroid already used by döner kebab and pide in this seed.
    lat: 41.0082,
    lng: 28.9784,
    countryName: "Turkey",
    isoCode: "TR",
    cuisineSlug: "turkish-cuisine",
    dishTypes: ["casserole", "main-course"],
    // en.wikipedia.org/wiki/Musakka redirects to Moussaka (verified 2026-07-25).
    wikipediaSlug: "Moussaka",
  },
  {
    slug: "pide",
    canonicalName: "Pide",
    shortDescription:
      "A Turkish boat-shaped flatbread topped with cheese, minced meat, vegetables, or egg and baked in a hot oven until the crust is crisp and the center remains tender.",
    lat: 41.0082,
    lng: 28.9784,
    countryName: "Turkey",
    isoCode: "TR",
    cuisineSlug: "turkish-cuisine",
    dishTypes: ["bread", "main-course"],
    wikipediaSlug: "Pide",
  },
  {
    slug: "manti",
    canonicalName: "Mantı",
    shortDescription:
      "Small Turkish dumplings filled with seasoned meat, boiled or steamed, and served with garlic yogurt, melted butter, dried mint, and red pepper.",
    lat: 39.9334,
    lng: 32.8597,
    countryName: "Turkey",
    isoCode: "TR",
    cuisineSlug: "turkish-cuisine",
    dishTypes: ["dumpling", "main-course"],
    wikipediaSlug: "Manti_(dumpling)",
  },
  {
    slug: "iskender-kebab",
    canonicalName: "İskender kebab",
    shortDescription:
      "A Bursa specialty of sliced döner meat over pieces of pide, covered with tomato sauce and melted butter and served with yogurt on the side.",
    lat: 40.195,
    lng: 29.06,
    countryName: "Turkey",
    isoCode: "TR",
    cuisineSlug: "turkish-cuisine",
    dishTypes: ["kebab", "main-course"],
    wikipediaSlug: "Iskender_kebab",
  },
  {
    slug: "samosa",
    canonicalName: "Samosa",
    shortDescription:
      "A crisp, triangular pastry filled with spiced potatoes, peas, lentils, meat, or vegetables and fried or baked across South Asia and its diaspora.",
    lat: 28.6139,
    lng: 77.209,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "indian-cuisine",
    dishTypes: ["appetizer", "street-snack"],
    wikipediaSlug: "Samosa",
  },
  {
    slug: "idli",
    canonicalName: "Idli",
    shortDescription:
      "Soft, steamed South Indian cakes made from a fermented batter of rice and black gram, traditionally served with sambar and coconut or tomato chutney.",
    lat: 13.0827,
    lng: 80.2707,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "south-indian-cuisine",
    dishTypes: ["pancake", "main-course"],
    wikipediaSlug: "Idli",
  },
  {
    slug: "vada",
    canonicalName: "Vada",
    shortDescription:
      "A South Asian savory fritter made from a ground legume or grain batter, shaped into rings or patties and fried until crisp outside and tender within.",
    lat: 13.0827,
    lng: 80.2707,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "south-indian-cuisine",
    dishTypes: ["appetizer", "street-snack"],
    wikipediaSlug: "Vada_(food)",
  },
  {
    slug: "chole-bhature",
    canonicalName: "Chole bhature",
    shortDescription:
      "A North Indian combination of spiced chickpea curry and bhature, a large, leavened, deep-fried bread served hot with pickles, onion, and chutney.",
    lat: 28.6139,
    lng: 77.209,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "indian-cuisine",
    dishTypes: ["curry", "bread", "main-course"],
    wikipediaSlug: "Chole_bhature",
  },
  {
    slug: "butter-chicken",
    canonicalName: "Butter chicken",
    shortDescription:
      "Roasted marinated chicken simmered in a smooth tomato, butter, and cream sauce seasoned with fenugreek and warm spices.",
    lat: 28.6139,
    lng: 77.209,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "indian-cuisine",
    dishTypes: ["curry", "main-course"],
    wikipediaSlug: "Butter_chicken",
  },
  {
    slug: "aloo-gobi",
    canonicalName: "Aloo gobi",
    shortDescription:
      "A dry Indian curry of potatoes and cauliflower cooked with turmeric, cumin, ginger, garlic, and other regional spices.",
    lat: 31.634,
    lng: 74.8723,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "indian-cuisine",
    dishTypes: ["curry", "main-course"],
    wikipediaSlug: "Aloo_gobi",
  },
  {
    slug: "masala-dosa",
    canonicalName: "Masala dosa",
    shortDescription:
      "A thin, crisp South Indian fermented rice-and-lentil crepe filled with a fragrant potato masala and served with sambar and chutney.",
    lat: 12.9716,
    lng: 77.5946,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "south-indian-cuisine",
    dishTypes: ["pancake", "main-course"],
    wikipediaSlug: "Masala_dosa",
  },
  {
    slug: "palak-paneer",
    canonicalName: "Palak paneer",
    shortDescription:
      "Cubes of fresh paneer cheese served in a smooth spinach sauce seasoned with ginger, garlic, green chili, and warming spices.",
    lat: 28.6139,
    lng: 77.209,
    countryName: "India",
    isoCode: "IN",
    cuisineSlug: "indian-cuisine",
    dishTypes: ["curry", "main-course"],
    wikipediaSlug: "Palak_paneer",
  },
  {
    slug: "tonkatsu",
    canonicalName: "Tonkatsu",
    shortDescription:
      "A Japanese breaded and deep-fried pork cutlet sliced into strips and served with tangy tonkatsu sauce, shredded cabbage, and rice.",
    lat: 35.6762,
    lng: 139.6503,
    countryName: "Japan",
    isoCode: "JP",
    cuisineSlug: "japanese-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Tonkatsu",
  },
  {
    slug: "soba",
    canonicalName: "Soba",
    shortDescription:
      "Japanese noodles made primarily from buckwheat flour, served chilled with dipping sauce or hot in a dashi-based broth with seasonal toppings.",
    lat: 35.6762,
    lng: 139.6503,
    countryName: "Japan",
    isoCode: "JP",
    cuisineSlug: "japanese-cuisine",
    dishTypes: ["noodle-soup", "main-course"],
    wikipediaSlug: "Soba",
  },
  {
    slug: "okonomiyaki",
    canonicalName: "Okonomiyaki",
    shortDescription:
      "A savory Japanese pancake of batter, cabbage, and chosen fillings cooked on a griddle and finished with okonomiyaki sauce, mayonnaise, seaweed, and bonito flakes.",
    lat: 34.6937,
    lng: 135.5023,
    countryName: "Japan",
    isoCode: "JP",
    cuisineSlug: "japanese-cuisine",
    dishTypes: ["pancake", "main-course"],
    wikipediaSlug: "Okonomiyaki",
  },
  {
    slug: "yakitori",
    canonicalName: "Yakitori",
    shortDescription:
      "Japanese chicken pieces and offal skewered on bamboo, grilled over charcoal, and seasoned with tare sauce or salt.",
    lat: 35.6762,
    lng: 139.6503,
    countryName: "Japan",
    isoCode: "JP",
    cuisineSlug: "japanese-cuisine",
    dishTypes: ["kebab", "street-snack"],
    wikipediaSlug: "Yakitori",
  },
  {
    slug: "tempura",
    canonicalName: "Tempura",
    shortDescription:
      "Seafood or vegetables lightly coated in a cold batter and quickly deep-fried to a delicate, crisp finish, then served with dipping sauce or salt.",
    lat: 35.6762,
    lng: 139.6503,
    countryName: "Japan",
    isoCode: "JP",
    cuisineSlug: "japanese-cuisine",
    dishTypes: ["appetizer", "main-course"],
    wikipediaSlug: "Tempura",
  },
  {
    slug: "takoyaki",
    canonicalName: "Takoyaki",
    shortDescription:
      "Round Japanese street-food batter cakes cooked in a molded pan around pieces of octopus and topped with sauce, mayonnaise, seaweed, and bonito flakes.",
    lat: 34.6937,
    lng: 135.5023,
    countryName: "Japan",
    isoCode: "JP",
    cuisineSlug: "japanese-cuisine",
    dishTypes: ["appetizer", "street-snack"],
    wikipediaSlug: "Takoyaki",
  },
  {
    slug: "gyoza",
    canonicalName: "Gyoza",
    shortDescription:
      "Japanese pan-fried dumplings with thin wrappers and a filling of pork, cabbage, garlic chives, and ginger, browned on one side and steamed to finish.",
    lat: 35.6762,
    lng: 139.6503,
    countryName: "Japan",
    isoCode: "JP",
    cuisineSlug: "japanese-cuisine",
    dishTypes: ["dumpling", "appetizer"],
    wikipediaSlug: "Gyoza",
  },
  {
    slug: "peking-duck",
    canonicalName: "Peking duck",
    shortDescription:
      "A Beijing preparation of air-dried and roasted duck with lacquered, crisp skin, carved tableside and wrapped in thin pancakes with scallions and sweet bean sauce.",
    lat: 39.9042,
    lng: 116.4074,
    countryName: "China",
    isoCode: "CN",
    cuisineSlug: "chinese-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Peking_duck",
  },
  {
    slug: "kung-pao-chicken",
    canonicalName: "Kung Pao chicken",
    shortDescription:
      "A Sichuan stir-fry of chicken, dried chilies, peanuts, scallions, and a savory-sweet sauce with the characteristic fragrance of Sichuan pepper.",
    lat: 30.5728,
    lng: 104.0668,
    countryName: "China",
    isoCode: "CN",
    cuisineSlug: "chinese-cuisine",
    dishTypes: ["stir-fry", "main-course"],
    wikipediaSlug: "Kung_Pao_chicken",
  },
  {
    slug: "xiaolongbao",
    canonicalName: "Xiaolongbao",
    shortDescription:
      "Delicate steamed soup dumplings from the Jiangnan region, filled with pork and savory aspic that melts into broth inside the wrapper.",
    lat: 31.2304,
    lng: 121.4737,
    countryName: "China",
    isoCode: "CN",
    cuisineSlug: "chinese-cuisine",
    dishTypes: ["dumpling", "appetizer"],
    wikipediaSlug: "Xiaolongbao",
  },
  {
    slug: "chow-mein",
    canonicalName: "Chow mein",
    shortDescription:
      "Chinese wheat noodles stir-fried with vegetables and a choice of meat, seafood, or tofu, with regional versions ranging from crisp to soft noodles.",
    lat: 22.3193,
    lng: 114.1694,
    countryName: "China",
    isoCode: "CN",
    cuisineSlug: "chinese-cuisine",
    dishTypes: ["stir-fry", "main-course"],
    wikipediaSlug: "Chow_mein",
  },
  {
    slug: "dan-dan-noodles",
    canonicalName: "Dan dan noodles",
    shortDescription:
      "Sichuan noodles dressed with a spicy sesame or peanut sauce, preserved mustard greens, chili oil, Sichuan pepper, scallions, and often minced pork.",
    lat: 30.5728,
    lng: 104.0668,
    countryName: "China",
    isoCode: "CN",
    cuisineSlug: "chinese-cuisine",
    dishTypes: ["noodle-soup", "main-course"],
    wikipediaSlug: "Dandan_noodles",
  },
  {
    slug: "char-siu",
    canonicalName: "Char siu",
    shortDescription:
      "Cantonese barbecued pork marinated in a glossy blend of maltose or honey, soy, fermented bean curd, and five-spice before being roasted and sliced.",
    lat: 23.1291,
    lng: 113.2644,
    countryName: "China",
    isoCode: "CN",
    cuisineSlug: "chinese-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Char_siu",
  },
  {
    slug: "tacos-al-pastor",
    canonicalName: "Tacos al pastor",
    shortDescription:
      "Mexican tacos of marinated pork cooked on a vertical spit, shaved onto small corn tortillas, and finished with onion, cilantro, salsa, and pineapple.",
    lat: 19.4326,
    lng: -99.1332,
    countryName: "Mexico",
    isoCode: "MX",
    cuisineSlug: "mexican-cuisine",
    dishTypes: ["street-snack", "main-course"],
    wikipediaSlug: "Al_pastor",
  },
  {
    slug: "mole-poblano",
    canonicalName: "Mole poblano",
    shortDescription:
      "A complex Mexican sauce from Puebla combining dried chilies, spices, nuts or seeds, aromatics, and chocolate, traditionally served over turkey or chicken.",
    lat: 19.0414,
    lng: -98.2063,
    countryName: "Mexico",
    isoCode: "MX",
    cuisineSlug: "mexican-cuisine",
    dishTypes: ["sauce", "main-course"],
    wikipediaSlug: "Mole_(sauce)",
  },
  {
    slug: "chiles-en-nogada",
    canonicalName: "Chiles en nogada",
    shortDescription:
      "Roasted poblano chiles stuffed with picadillo, covered in a walnut cream sauce, and garnished with pomegranate and parsley in the colors of the Mexican flag.",
    lat: 19.0414,
    lng: -98.2063,
    countryName: "Mexico",
    isoCode: "MX",
    cuisineSlug: "mexican-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Chiles_en_nogada",
  },
  {
    slug: "arepa",
    canonicalName: "Arepa",
    shortDescription:
      "A griddled or baked cornmeal cake from northern South America, split and filled or topped with cheese, meat, beans, avocado, or eggs.",
    lat: 4.711,
    lng: -74.0721,
    countryName: "Colombia",
    isoCode: "CO",
    cuisineSlug: "colombian-cuisine",
    dishTypes: ["bread", "main-course"],
    wikipediaSlug: "Arepa",
  },
  {
    slug: "bandeja-paisa",
    canonicalName: "Bandeja paisa",
    shortDescription:
      "A substantial Colombian platter of beans, rice, ground meat, chicharrón, fried egg, plantain, avocado, and arepa associated with the Antioquia region.",
    lat: 6.2442,
    lng: -75.5812,
    countryName: "Colombia",
    isoCode: "CO",
    cuisineSlug: "colombian-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Bandeja_paisa",
  },
  {
    slug: "lomo-saltado",
    canonicalName: "Lomo saltado",
    shortDescription:
      "A Peruvian-Chinese chifa stir-fry of beef, tomatoes, onions, soy sauce, and cilantro served with rice and french fries.",
    lat: -12.0464,
    lng: -77.0428,
    countryName: "Peru",
    isoCode: "PE",
    cuisineSlug: "peruvian-cuisine",
    dishTypes: ["stir-fry", "main-course"],
    wikipediaSlug: "Lomo_saltado",
  },
  {
    slug: "anticuchos",
    canonicalName: "Anticuchos",
    shortDescription:
      "Peruvian skewers, traditionally made with marinated beef heart, grilled over charcoal and served with potatoes, corn, or a bright chili sauce.",
    lat: -12.0464,
    lng: -77.0428,
    countryName: "Peru",
    isoCode: "PE",
    cuisineSlug: "peruvian-cuisine",
    dishTypes: ["kebab", "street-snack"],
    wikipediaSlug: "Anticucho",
  },
  {
    slug: "arroz-con-pollo",
    canonicalName: "Arroz con pollo",
    shortDescription:
      "A Latin American rice-and-chicken dish in which rice is cooked with sofrito, stock, herbs, and vegetables around browned chicken pieces.",
    lat: -12.0464,
    lng: -77.0428,
    countryName: "Peru",
    isoCode: "PE",
    cuisineSlug: "peruvian-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Arroz_con_pollo",
  },
  {
    slug: "choripan",
    canonicalName: "Choripán",
    shortDescription:
      "An Argentine street-food sandwich of grilled chorizo in a crusty roll, usually finished with chimichurri and salsa criolla.",
    lat: -34.6037,
    lng: -58.3816,
    countryName: "Argentina",
    isoCode: "AR",
    cuisineSlug: "argentine-cuisine",
    dishTypes: ["sandwich", "street-snack"],
    wikipediaSlug: "Chorip%C3%A1n",
  },
  {
    slug: "asado",
    canonicalName: "Asado",
    shortDescription:
      "The Argentine tradition of grilling beef and other meats over wood or charcoal, with slow cooking, simple seasoning, and chimichurri at the table.",
    lat: -34.6037,
    lng: -58.3816,
    countryName: "Argentina",
    isoCode: "AR",
    cuisineSlug: "argentine-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Asado",
  },
  {
    slug: "humita",
    canonicalName: "Humita",
    shortDescription:
      "A South American preparation of fresh corn, onion, and spices ground or grated into a savory mixture, wrapped in corn husks, and steamed or baked.",
    lat: -34.6037,
    lng: -58.3816,
    countryName: "Argentina",
    isoCode: "AR",
    cuisineSlug: "argentine-cuisine",
    dishTypes: ["appetizer", "main-course"],
    wikipediaSlug: "Humita",
  },
  {
    slug: "lechon",
    canonicalName: "Lechon",
    shortDescription:
      "A festive Filipino whole-roasted pig cooked slowly over charcoal until the meat is tender and the skin is deeply crisp, served with liver sauce or vinegar.",
    lat: 14.5995,
    lng: 120.9842,
    countryName: "Philippines",
    isoCode: "PH",
    cuisineSlug: "filipino-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Lechon",
  },
  {
    slug: "adobo-filipino",
    canonicalName: "Filipino adobo",
    shortDescription:
      "A Filipino braise of meat, seafood, or vegetables simmered in vinegar, soy sauce, garlic, bay leaf, and black pepper until deeply savory and tender.",
    lat: 14.5995,
    lng: 120.9842,
    countryName: "Philippines",
    isoCode: "PH",
    cuisineSlug: "filipino-cuisine",
    dishTypes: ["stew", "main-course"],
    wikipediaSlug: "Philippine_adobo",
  },
  {
    slug: "sinigang",
    canonicalName: "Sinigang",
    shortDescription:
      "A Filipino sour soup of meat, seafood, or vegetables in a tamarind-based broth with tomatoes, onions, and local greens.",
    lat: 14.5995,
    lng: 120.9842,
    countryName: "Philippines",
    isoCode: "PH",
    cuisineSlug: "filipino-cuisine",
    dishTypes: ["soup", "main-course"],
    wikipediaSlug: "Sinigang",
  },
  {
    slug: "kare-kare",
    canonicalName: "Kare-kare",
    shortDescription:
      "A Filipino peanut-based stew of oxtail, beef, or vegetables thickened with ground peanuts and toasted rice, traditionally served with fermented shrimp paste.",
    lat: 14.5995,
    lng: 120.9842,
    countryName: "Philippines",
    isoCode: "PH",
    cuisineSlug: "filipino-cuisine",
    dishTypes: ["stew", "main-course"],
    wikipediaSlug: "Kare-kare",
  },
  {
    slug: "halo-halo",
    canonicalName: "Halo-halo",
    shortDescription:
      "A Filipino shaved-ice dessert layered with sweet beans, fruit, jellies, leche flan, evaporated milk, and often a scoop of ice cream.",
    lat: 14.5995,
    lng: 120.9842,
    countryName: "Philippines",
    isoCode: "PH",
    cuisineSlug: "filipino-cuisine",
    dishTypes: ["dessert"],
    wikipediaSlug: "Halo-halo",
  },
  {
    slug: "satay",
    canonicalName: "Satay",
    shortDescription:
      "Skewers of marinated meat grilled over charcoal and served with a rich peanut sauce, lontong or rice cakes, and fresh pickles across Southeast Asia.",
    lat: -6.2088,
    lng: 106.8456,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["kebab", "street-snack"],
    wikipediaSlug: "Satay",
  },
  {
    slug: "ikan-bakar",
    canonicalName: "Ikan bakar",
    shortDescription:
      "Indonesian grilled fish rubbed with a sweet-spicy spice paste, cooked over charcoal, and served with sambal, lime, and rice.",
    lat: -6.2088,
    lng: 106.8456,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["main-course"],
    wikipediaSlug: "Ikan_bakar",
  },
  {
    slug: "sambal",
    canonicalName: "Sambal",
    shortDescription:
      "A family of Indonesian and Southeast Asian chili relishes made by pounding fresh or dried chilies with aromatics, acid, salt, and sometimes shrimp paste or fruit.",
    lat: -6.2088,
    lng: 106.8456,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["sauce", "appetizer"],
    wikipediaSlug: "Sambal",
  },
  {
    slug: "martabak",
    canonicalName: "Martabak",
    shortDescription:
      "An Indonesian stuffed pancake with savory egg, meat, and scallion fillings or a thick sweet version layered with chocolate, peanuts, cheese, or condensed milk.",
    lat: -6.2088,
    lng: 106.8456,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["pancake", "street-snack"],
    wikipediaSlug: "Martabak",
  },
  {
    slug: "bakso",
    canonicalName: "Bakso",
    shortDescription:
      "Indonesian meatballs made from beef, chicken, or fish, served in a clear noodle soup with greens, tofu, fried shallots, and chili sauce.",
    lat: -6.2088,
    lng: 106.8456,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["soup", "main-course"],
    wikipediaSlug: "Bakso",
  },
  {
    slug: "bubur-ayam",
    canonicalName: "Bubur ayam",
    shortDescription:
      "An Indonesian chicken rice porridge topped with shredded chicken, scallions, fried shallots, crackers, soy sauce, and sometimes a soft-boiled egg.",
    lat: -6.2088,
    lng: 106.8456,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["soup", "main-course"],
    wikipediaSlug: "Bubur_ayam",
  },
  {
    slug: "nasi-padang",
    canonicalName: "Nasi Padang",
    shortDescription:
      "A Minangkabau rice meal served with an assortment of rich curries, vegetables, sambal, and meat or fish dishes, named for the city of Padang.",
    lat: -0.9471,
    lng: 100.4172,
    countryName: "Indonesia",
    isoCode: "ID",
    cuisineSlug: "indonesian-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Nasi_padang",
  },
  {
    slug: "injera",
    canonicalName: "Injera",
    shortDescription:
      "A sour, spongy Ethiopian flatbread made from fermented teff batter and used as both a plate and utensil for stews, vegetables, and meat.",
    lat: 9.032,
    lng: 38.7469,
    countryName: "Ethiopia",
    isoCode: "ET",
    cuisineSlug: "ethiopian-cuisine",
    dishTypes: ["bread", "main-course"],
    wikipediaSlug: "Injera",
  },
  {
    slug: "doro-wat",
    canonicalName: "Doro wat",
    shortDescription:
      "A richly spiced Ethiopian chicken stew with onions, berbere, clarified butter, and boiled eggs, traditionally eaten with injera.",
    lat: 9.032,
    lng: 38.7469,
    countryName: "Ethiopia",
    isoCode: "ET",
    cuisineSlug: "ethiopian-cuisine",
    dishTypes: ["stew", "main-course"],
    wikipediaSlug: "Doro_wat",
  },
  {
    slug: "bulgur",
    canonicalName: "Bulgur",
    shortDescription:
      "Parboiled, dried, and cracked wheat used as a staple grain in pilafs, salads, kibbeh, and stuffed vegetables across the Middle East and Mediterranean.",
    lat: 33.8938,
    lng: 35.5018,
    countryName: "Lebanon",
    isoCode: "LB",
    cuisineSlug: "lebanese-cuisine",
    dishTypes: ["rice-dish", "main-course"],
    wikipediaSlug: "Bulgur",
  },
  {
    slug: "focaccia",
    canonicalName: "Focaccia",
    shortDescription:
      "A thick Italian flatbread enriched with olive oil, dimpled before baking, and commonly finished with salt, rosemary, olives, tomatoes, or onions.",
    lat: 44.4056,
    lng: 8.9463,
    countryName: "Italy",
    isoCode: "IT",
    cuisineSlug: "italian-cuisine",
    dishTypes: ["bread", "appetizer"],
    wikipediaSlug: "Focaccia",
  },
];
